version: 2
jobs:
  deploy-artifactory:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - run: git config --global user.email "circleci@entur.no"
    - run: git config --global user.name "circleci"
    - checkout
    - run: mvn release:prepare -B -s /tools/m2/settings.xml
    - run: mvn release:perform -B -s /tools/m2/settings.xml

workflows:
  version: 2
  build_deploy:
    jobs:
    - deploy-artifactory:
        context: org-carbon
        #filters:
        #  branches:
        #    only: master
