version: 2
jobs:
  deploy-artifactory:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - run: mvn deploy -s /tools/m2/settings.xml -DskipTests
workflows:
  version: 2
  build_deploy:
    jobs:
    - deploy-artifactory:
        context: org-carbon
        filters:
          branches:
            only: master
