version: 2
jobs:
  deploy-artifactory:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: git config --global user.email "circleci@entur.no"
      - run: git config --global user.name "circleci"
      - checkout
      - run:
          name: Download Maven settings
          command: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
      - run: mvn gitflow:release -B -s .circleci/settings.xml -DargLine='-s .circleci/settings.xml' -DpostReleaseGoals=deploy -DskipTestProject=true

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy-artifactory:
          context:
            - org-carbon
            - global
          filters:
            branches:
              only: master
