version: 2
jobs:
  deploy-artifactory:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - add_ssh_keys:
        fingerprints:
          - "93:21:23:57:a1:3a:ba:64:68:49:f2:9a:d2:58:19:d1"
    - checkout
    - run: mvn release:prepare -B -s /tools/m2/settings.xml
    - run: mvn release:perform -B -s /tools/m2/settings.xml

workflows:
  version: 2
  build_deploy:
    jobs:
    - deploy-artifactory:
        context: org-carbon
        #filters:
        #  branches:
        #    only: master
