version: 2
jobs:
  deploy-artifactory:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - add_ssh_keys:
      fingerprints:
      - "fd:67:09:2a:3f:a1:33:e0:22:55:e1:ed:f1:7a:d3:87"
    - checkout
    - run: mvn release:prepare -s /tools/m2/settings.xml
    - run: mvn release:perform -s /tools/m2/settings.xml

workflows:
  version: 2
  build_deploy:
    jobs:
    - deploy-artifactory:
        context: org-carbon
        #filters:
        #  branches:
        #    only: master
